### ISSUE TITLE
Sitecore 7.0 and above

### ISSUE THREAD

**Issue by thehereward** [adoprog/Sitecore-Courier#16]
Sitecore Courier currently only supports Sitecore up to version 6.5.

Does anyone know how difficult it would be to adapt it to work with more recent versions of Sitecore?

_(The package formats do not look hugely different but I thought I would ask if anyone had already tried this before embarking on too much of an adventure.)_

**Comment by adoprog** [comment]
Hi,

I think it should work on any version. If it does not work on 8.x - please let me know!

**Comment by thehereward** [comment]
That's interesting. I've been working with Sitecore 7.0 and have not been able to get this to work. I can generate packages quite happily but when importing them to Sitecore it silently fails to update anything. I had assumed it was a slight different in package format between major versions of Sitecore but it may just be me not setting things up correctly. Do you have any ideas what could be causing this?

We are probably switching to 8.1 very soon so I will give it another go. Any help you can provide would be very useful!

**Comment by adoprog** [comment]
The package format hasn't changed, maybe there was something wrong with the package content, or the target machine. In any of the cases - please report any issues :)
