### ISSUE TITLE
Adding security details to the .update packages

### ISSUE THREAD

**Issue by yaroskrinitskiy** [adoprog/Sitecore-Courier#21]
At the moment it's impossible to add users/roles to the update package using Sitecore Courier. 

For instance, if I have a serialization folder that contains items serialized using Unicorn and it also contains serialized Roles/Users - I will get the exception running the 
Sitecore.Courier.Runner.exe -s %output%\empty -t %projectpath%\..\serialization -o %output%\Items.update -r
command.

**Comment by adoprog** [comment]
Implemented initial version https://github.com/adoprog/Sitecore-Courier/pull/41. Does not change standard behavior unless "-i" flag is passed.
Will be released/documented after testing.
