### ISSUE TITLE
DiffGenerator

### ISSUE THREAD

**Issue by Eldblom** [adoprog/Sitecore-Courier#22]
https://github.com/adoprog/Sitecore-Courier/blob/master/Sitecore.Courier/DIffGenerator.cs#L20

In this line target and source is reversed. Is this deliberately or just confusing? :)

**Comment by adoprog** [comment]
Thanks! Fixed it. 
Luckily, it did not affect anything because both methods instantiated Sitecore.Update.Data.DataManager (defined in App.config).
