### ISSUE TITLE
Update Chocolatey to Version 1.2

### ISSUE THREAD

**Issue by benamaster** [adoprog/Sitecore-Courier#26]
Version 1.0 is still on Chocolatey, this should be updated to 1.2.

https://chocolatey.org/packages/sitecore-courier

**Comment by adoprog** [comment]
Done https://chocolatey.org/packages/sitecore-courier/1.2.0 (might be still in review for some time, but "choco upgrade sitecore-courier --version 1.2.0" already works)

**Comment by adoprog** [comment]
Thanks for bringing this up @benamaster :)
