### ISSUE TITLE
Collision Behavior not working

### ISSUE THREAD

**Issue by benamaster** [adoprog/Sitecore-Courier#27]
When using -c force the following error is displayed. I've tried -b force as well as --collisionBehavior force and none work.

```
C:\Users\Administrator\Downloads\Sitecore.Courier.Runner>Sitecore.Courier.Runner
.exe -c force -r true -t C:\Unicorn17 -o C:\Unicorn17\Unicorn.update
```
Source:
Target: C:\Unicorn17
Output: C:\Unicorn17\Unicorn.update
Collision behavior: Undefined
Configuration: force
Path to project file:

Unhandled Exception: System.NullReferenceException: ScProjectFilePath is require
d if Build Configuration is provided.
   at Sitecore.Courier.Runner.ExclusionHandler.HasValidExclusions(String buildCo
nfiguration, String xmlFilePath) in C:\Source\Repos\Sitecore-Courier\Sitecore.Co
urier.Runner\ExclusionHandler.cs:line 62
   at Sitecore.Courier.Runner.Program.Main(String[] args) in C:\Source\Repos\Sit
ecore-Courier\Sitecore.Courier.Runner\Program.cs:line 19

**Comment by benamaster** [comment]
Also tried the following

`Sitecore.Courier.Runner.exe --target C:\Unicorn17 --output C:\Unicorn17\Unicorn.update --collisionBehavior force --rainbow true `

**Comment by adoprog** [comment]
@benamaster There is a conflicting short name, I've replaced "c" command with "b", i.e. please use '-b force' now.

**Comment by adoprog** [comment]
https://github.com/adoprog/Sitecore-Courier/releases/tag/1%2C2%2C1
