### ISSUE TITLE
Update PowerShell Gallery to latest version

### ISSUE THREAD

**Issue by jflheureux** [adoprog/Sitecore-Courier#35]
In the readme file, there is a link to install Sitecore Courier from the PowerShell Gallery: https://www.powershellgallery.com/packages/Sitecore.Courier/1.0

However, this version is outdated.

Could you please update it to the latest version and ensure it is updated at each new release?

Thanks

**Comment by adoprog** [comment]
Thanks! Updated it.

**Comment by jflheureux** [comment]
Thank you very much!
