### ISSUE TITLE
"The system cannot find the file specified" error when right clicking in context menu on folder

### ISSUE THREAD

**Issue by ivanbuzyka** [adoprog/Sitecore-Courier#8]
To reproduce:
1. Install Sitecore-Courier using choco (Windows 8.1)
2. Restart PC
3. Right click on any folder and choose "Package with Sitecore courier option".

An exception occurred: "The system cannot find the file specified"

**Comment by adoprog** [comment]
Could you please provide some more details? Maybe stack trace or something like this?
Just a guess - maybe some .NET Framework version is missing?

**Comment by ivanbuzyka** [comment]
Just tried one more time. Only see this window (see attachment)
![2015-02-03_1037](https://cloud.githubusercontent.com/assets/2214435/6017739/2b3460ae-ab91-11e4-94d7-8f36004768db.png)
There is nothing in Win Event Logs. Is there somewhere log file of Courier?
I have .NET 3.5 as well as 4.5 installed.

**Comment by chandreshr** [comment]
I had faced similar issues, Please double check the database configuration (connection strings) and make sure database services are running.
