### ISSUE TITLE
Default conflict management in package

### ISSUE THREAD

**Issue by ullmark** [adoprog/Sitecore-Courier#9]
Hello,
Apparently a sitecore "update" package can contain information on how to handle conflicts when installing a package. So if the package is installed programmatically you could have "overwrite" as merge method. 

Is it possible to configure this in Sitecore Courier somehow? 

Thanks.

**Comment by yannisgu** [comment]
At the moment you can do this by seting `<forceoverwrites>true</forceoverwrites>` in the app.config. #11 would add a command line option.
